from python: 3.11.4

WORKDIR C:\Users\Irene\proyecto
 
COPY C:\Users\Irene\proyecto\ireneglz10/alexa-jardin-.git

RUN pip install -r requirements.txt 

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]